const express = require('express');
const authRoutes = require('./auth');
const userRoutes = require('./users');
const vendorRoutes = require('./vendor');
const productRoutes = require('./products');
const variantRoutes = require('./variants');
const imageRoutes = require('./images');
const categoryRoutes = require('./categories');
const cartRoutes = require('./cart');
const wishlistRoutes = require('./wishlist');
const addressRoutes = require('./addresses');
const couponRoutes = require('./coupons');
const orderRoutes = require('./orders');
const shipmentRoutes = require('./shipments');
const returnRoutes = require('./returns');
const paymentRoutes = require('./payments');
const notificationRoutes = require('./notifications');
const chatRoutes = require('./chat');
const auditRoutes = require('./audit');
const inventoryRoutes = require('./inventory');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/vendor', vendorRoutes);
router.use('/products', productRoutes);
router.use('/variants', variantRoutes);
router.use('/images', imageRoutes);
router.use('/categories', categoryRoutes);
router.use('/cart', cartRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/addresses', addressRoutes);
router.use('/coupons', couponRoutes);
router.use('/orders', orderRoutes);
router.use('/shipments', shipmentRoutes);
router.use('/returns', returnRoutes);
router.use('/payments', paymentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/chat', chatRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/inventory', inventoryRoutes);

module.exports = router;
